"""Added Student model

Revision ID: 8a82fe762b4a
Revises: aee9cafe8aa5
Create Date: 2024-04-05 14:40:32.947448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a82fe762b4a'
down_revision = 'aee9cafe8aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
